FROM python:3.5-alpine

# HEALTHCHECK --interval=5m --timeout=3s \
#   CMD curl -f http://localhost:8080/ || exit 1

RUN apk add --no-cache --virtual .build-dependencies \
 git \
 gcc \
 python3-dev \
 linux-headers \
 musl-dev \
 libffi-dev \
 openssl-dev

RUN mkdir -p /opt/app-root/src
WORKDIR /opt/app-root/src

# RUN apk del .build-dependencies

COPY s2i/run /usr/local/bin/run

CMD /usr/local/bin/run
