FROM python:3.5-alpine

RUN apk add --no-cache \
 git \
 gcc \
 python3-dev \
 linux-headers \
 musl-dev \
 libffi-dev \
 openssl-dev

RUN mkdir -p /opt/app-root/src
WORKDIR /opt/app-root/src

# RUN apk del .build-dependencies

COPY s2i/run /usr/local/bin/run

CMD /usr/local/bin/run
