FROM centos/python-35-centos7

# Set a privileged user to install another dependencies
USER root
RUN yum -y install epel-release &&\
    yum install -y libffi-devel &&\
    yum clean all -y


ONBUILD COPY requirements.txt /opt/app-root/src
ONBUILD RUN /bin/bash -c "pip install --no-cache-dir -r requirements.txt"
ONBUILD COPY . /opt/app-root/src

# This default user after all instalation
USER 1001

CMD $STI_SCRIPTS_PATH/run